// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3MvKes_d6TRGpu00JYgDpMNP8xDVTvwk',
    appId: '1:204056403715:web:25ba21906b4818441a1336',
    messagingSenderId: '204056403715',
    projectId: 'pegion-18fd4',
    authDomain: 'pegion-18fd4.firebaseapp.com',
    storageBucket: 'pegion-18fd4.appspot.com',
    measurementId: 'G-Z9J8XE59K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjrq18e79D1Z6gpwHz89k3eiMNle_r3xw',
    appId: '1:204056403715:android:a67860f1e0d2a6d31a1336',
    messagingSenderId: '204056403715',
    projectId: 'pegion-18fd4',
    storageBucket: 'pegion-18fd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzF2grGNspZllF2rGdyg3Bs4LCZBfy6Jo',
    appId: '1:204056403715:ios:d877f67e2bd6bda31a1336',
    messagingSenderId: '204056403715',
    projectId: 'pegion-18fd4',
    storageBucket: 'pegion-18fd4.appspot.com',
    iosBundleId: 'com.example.pegion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzF2grGNspZllF2rGdyg3Bs4LCZBfy6Jo',
    appId: '1:204056403715:ios:f9c13a5d857eaa4d1a1336',
    messagingSenderId: '204056403715',
    projectId: 'pegion-18fd4',
    storageBucket: 'pegion-18fd4.appspot.com',
    iosBundleId: 'com.example.pegion.RunnerTests',
  );
}
